#.travis.yml

language: node_js
node_js:
  - "10.14"

branches:
  only:
    - update-angular

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
